/// Daily briefing — payload generated by Edge Function `daily-briefing`.
class Briefing {
  final String courtierId;
  final DateTime generatedAt;
  final List<BriefingProspect> newLeads;
  final List<BriefingProspect> hotProspects;
  final List<BriefingRelance> pendingRelances;
  final int unreadThreads;
  final int yesterdayQualified;

  const Briefing({
    required this.courtierId,
    required this.generatedAt,
    required this.newLeads,
    required this.hotProspects,
    required this.pendingRelances,
    required this.unreadThreads,
    required this.yesterdayQualified,
  });

  factory Briefing.fromJson(Map<String, dynamic> j) => Briefing(
        courtierId: j['courtier_id'] as String,
        generatedAt: DateTime.parse(j['generated_at'] as String),
        newLeads: ((j['new_leads'] as List?) ?? []).map((e) => BriefingProspect.fromJson(e as Map<String, dynamic>)).toList(),
        hotProspects: ((j['hot_prospects'] as List?) ?? []).map((e) => BriefingProspect.fromJson(e as Map<String, dynamic>)).toList(),
        pendingRelances: ((j['pending_relances'] as List?) ?? []).map((e) => BriefingRelance.fromJson(e as Map<String, dynamic>)).toList(),
        unreadThreads: (j['unread_threads'] as num?)?.toInt() ?? 0,
        yesterdayQualified: (j['yesterday_qualified'] as num?)?.toInt() ?? 0,
      );
}

class BriefingProspect {
  final String id;
  final String? nom;
  final int score;
  final String? secteur;
  final int? budget;
  final String? type;

  const BriefingProspect({required this.id, required this.score, this.nom, this.secteur, this.budget, this.type});

  factory BriefingProspect.fromJson(Map<String, dynamic> j) => BriefingProspect(
        id: j['id'] as String,
        nom: j['nom'] as String?,
        score: (j['score'] as num?)?.toInt() ?? 0,
        secteur: j['secteur'] as String?,
        budget: (j['budget'] as num?)?.toInt(),
        type: j['type'] as String?,
      );
}

class BriefingRelance {
  final String id;
  final String? prospectName;
  final String step;
  final DateTime scheduledFor;

  const BriefingRelance({required this.id, required this.step, required this.scheduledFor, this.prospectName});

  factory BriefingRelance.fromJson(Map<String, dynamic> j) => BriefingRelance(
        id: j['id'] as String,
        prospectName: j['prospect_name'] as String?,
        step: j['step'] as String? ?? 'j2',
        scheduledFor: DateTime.parse(j['scheduled_for'] as String),
      );
}
